//const game = new Game(["a", "b"], [new Card(WERT.ASS, FARBE.EICHEL), new Card(WERT.SIEBEN, FARBE.SCHELLEN)], [], [], -1, "a");
const game = new Game([new Player("A"), new Player("B"), new Player("C")], createDeck(), [], [], 0, new Player("H"));
document.getElementById("before").innerHTML = game.deck.toString();
game.shuffleDeck(game.deck);
game.GiveThree();
game.GiveThree();
game.GiveThree();
document.getElementById("after").innerHTML = game.deck.toString();
document.getElementById("A").innerHTML = game.players[0];
document.getElementById("B").innerHTML = game.players[1];
document.getElementById("C").innerHTML = game.players[2];